version: '3.8'

volumes:
  postgres-volume:

networks:
  postgres-network:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.10-bullseye
        USERNAME: vscode
        USER_UID: 1000
    restart: unless-stopped
    ports:
      - '3103:3103'
    env_file:
      - ./.env
    networks:
      - postgres-network
    user: vscode
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-bullseye
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4:6.2
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - ./.env
    networks:
      - postgres-network
    depends_on:
      - postgres
